// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2i3xzRpV7CUaUZklxES1fidTtqqOCT_g',
    appId: '1:19900626399:web:865a514e6090879841406a',
    messagingSenderId: '19900626399',
    projectId: 'metrogestion',
    authDomain: 'metrogestion.firebaseapp.com',
    storageBucket: 'metrogestion.firebasestorage.app',
    measurementId: 'G-7BHDYR4CXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM1uLGx9sc0z025pqDnidICmHo9HELJYY',
    appId: '1:19900626399:android:fb49fcc628e9a1d541406a',
    messagingSenderId: '19900626399',
    projectId: 'metrogestion',
    storageBucket: 'metrogestion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9kyZVMbv8OusQsiIyjZ3qwzvnMEOLvog',
    appId: '1:19900626399:ios:0d169067d224262d41406a',
    messagingSenderId: '19900626399',
    projectId: 'metrogestion',
    storageBucket: 'metrogestion.firebasestorage.app',
    iosBundleId: 'com.example.metroGestionProyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9kyZVMbv8OusQsiIyjZ3qwzvnMEOLvog',
    appId: '1:19900626399:ios:0d169067d224262d41406a',
    messagingSenderId: '19900626399',
    projectId: 'metrogestion',
    storageBucket: 'metrogestion.firebasestorage.app',
    iosBundleId: 'com.example.metroGestionProyecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2i3xzRpV7CUaUZklxES1fidTtqqOCT_g',
    appId: '1:19900626399:web:e6e1f709a8e682ac41406a',
    messagingSenderId: '19900626399',
    projectId: 'metrogestion',
    authDomain: 'metrogestion.firebaseapp.com',
    storageBucket: 'metrogestion.firebasestorage.app',
    measurementId: 'G-1FZT2VSHYQ',
  );
}
